### ISSUE TITLE
Move netlify information to deploy branch

### ISSUE THREAD

**Issue by jstarry** [yewstack/yew-wasm-pack-template#22]
#### Problem
The netlify directory is not useful for devs that clone the template project. It shouldn't be in the master branch.

#### Proposed Changes
* Remove netlify directory from `master` branch
* Use `deploy` branch for netlify deploys
* Create github action that merges master to netlify when the "Check" action succeeds
* Modify github "Deploy" action to deploy from the `deploy` branch

**Comment by shinglyu** [comment]
When I tried to create the project, I got the following error:

```
% cargo generate --git https://github.com/yewstack/yew-wasm-pack-template
 Project Name: Test
 Renaming project called `Test` to `test`...
 Creating project called `test`...
Error:  Error replacing placeholders `/tmp/test/.github/workflows/deploy.yml`
Info: caused by liquid: Unknown variable
  with:
    requested variable=secrets
    available variables=authors, crate_name, project-name
```

Maybe it's related to netlify?

**Comment by ankhers** [comment]
@shinglyu It is only indirectly related to netlify. It is because `cargo-generate` errors out when seeing variables it does not expect. And GitHub uses the `${{ foo }}` syntax for [contexts and expressions](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions). This conflicts with `cargo-generate` using the liquid template engine to replace variables using the `{{ foo }}` syntax.

You can follow a discussion at ashleygwilliams/cargo-generate#204. There are a couple linked PRs suggesting fixes.
